### ISSUE TITLE
Can't figure out how to change my project's website

### ISSUE THREAD

**Issue by dwightnaylor** [rcos/Observatory3#324] opened 2015-12-11 04:39 UTC
www.google.com isn't really good for us anymore.

We'd rather have tinyurl.com/moaprcos

**Comment by seveibar** [comment] 2015-12-11 15:18
Hey @vkr96 could you look at this? I know you made some changes with editting projects (or was that profiles?)

**Comment by vkr96** [comment] 2015-12-11 15:49
Okey dokey

**Comment by seveibar** [comment] 2015-12-11 16:26
thanks :)

**Comment by bennyty** [comment] 2015-12-11 17:38
Any PR that closes this should also close issue #320.

**Comment by kmcnellis** [comment] 2016-03-09 01:24
Duplicate of #190

**Comment by agundy** [comment] 2016-04-05 19:50
Fixed.

**Closed by agundy** 2016-04-05 19:50 UTC
Labels: duplicate, enhancement, pull request created, ui/ux
