### ISSUE TITLE
Problem with Observatory Description 

### ISSUE THREAD

**Issue by vkr96** [rcos/Observatory3#510] opened 2016-10-28 20:26 UTC
![screenshot from 2016-10-28 16-22-11](https://cloud.githubusercontent.com/assets/10600418/19821184/09decb64-9d2b-11e6-88e8-70a1c1f02365.png)

Why is the ###Description there and the ####Alternatives there? Is that a bug or was there some error in how the description was written in?

**Comment by agundy** [comment] 2016-10-28 20:43
That text block is supposed to be in markdown. Looks like it doesn't work

**Comment by kmcnellis** [comment] 2016-10-30 18:31
working for me
![screen shot 2016-10-30 at 2 30 48 pm](https://cloud.githubusercontent.com/assets/5566205/19838828/9624ab4c-9ead-11e6-9fc4-c748e42584c5.png)

**Comment by kmcnellis** [comment] 2016-10-30 18:32
Its working in the project page 
![screen shot 2016-10-30 at 2 30 48 pm](https://cloud.githubusercontent.com/assets/5566205/19838832/a7bcfde6-9ead-11e6-8bda-39c765449d29.png)

**Comment by kmcnellis** [comment] 2017-01-28 03:29
Related to #511

**Comment by kmcnellis** [comment] 2017-01-28 03:31
Duplicate of #471

**Closed by kmcnellis** 2017-01-28 03:31 UTC
Labels: bug, ui/ux
