### ISSUE TITLE
Project links should be editable.

### ISSUE THREAD

**Issue by bennyty** [rcos/Observatory3#320] opened 2015-12-04 21:38 UTC
Project links are currently permanent; once you set up a project there is no way to ever change what website and which repository the project points to. Our project (Suggestr) has changed both what domain name we are hosted under and which repository we are using. This is an important feature for us and for the future of other projects.

**Comment by kmcnellis** [comment] 2016-03-09 01:35
Duplicate of #190

**Comment by agundy** [comment] 2016-04-05 19:50
Fixed.

**Closed by agundy** 2016-04-05 19:50 UTC
Labels: duplicate, enhancement, pull request created, ui/ux
