### ISSUE TITLE
Broken Project Page

### ISSUE THREAD

**Issue by astonshane** [rcos/Observatory3#174] opened 2015-09-29 21:17 UTC
The Eve Online Market Analysis Tool team set up their project page incorrectly, and now clicking on their project or on their blog from the main project page (rcos.io/projects) just redirects to rcos.io. 
As a result, they can't add members to the page or edit their blog.

They fixed this by just creating a new project page.

**Comment by agundy** [comment] 2015-09-30 00:46
Will look into. Thanks!

**Comment by kmcnellis** [comment] 2016-03-09 01:24
Duplicate of #190

**Comment by kmcnellis** [comment] 2016-04-15 15:18
Fixed manually, needs something like #404 to prevent. Duplicate of #353

**Closed by kmcnellis** 2016-04-15 15:18 UTC
Labels: bug, duplicate
