### ISSUE TITLE
Edit attendance from Admin/users page

### ISSUE THREAD

**Issue by Bad-Science** [rcos/Observatory3#547] opened 2016-12-02 23:02 UTC
Not a huge priority, but it would be nice to be able to edit large group, small group, and bonus session attendance through this interface.

**Comment by yongabyte** [comment] 2016-12-02 23:56
If you meant adding attendances manually on the user page, @SaswatB had that feature implemented recently via #530

**Comment by vkr96** [comment] 2016-12-11 20:09
The problem is that when he was editing it how to do it was not apparent at all from the UI. 
@Bad-Science were you able to see any sort of button or something like that when you were trying to do this?

**Comment by yongabyte** [comment] 2016-12-11 23:44
@vkr96 
Sorry I wasn't being very clear. I meant the similar feature has been implemented, but it's not out on the live server yet at that time.
I don't think admins were able to edit any kind attendance on the admin/user page.

**Comment by Bad-Science** [comment] 2016-12-12 18:22
@vkr96 @yongabyte I did not see the option available but its possible I just don't know what I'm doing.

**Comment by kmcnellis** [comment] 2016-12-12 20:27
Currently there is only a feature to add manual attendances in the admin panel (and no way to review or remove them)

**Comment by kmcnellis** [comment] 2017-02-12 07:56
Specifically, we need to now remove attendance

**Comment by yongabyte** [comment] 2017-06-04 18:42
closed by #657

**Closed by yongabyte** 2017-06-04 18:42 UTC
Labels: feature request
